### ISSUE TITLE
How to stop the cell being resized out of the parent element?

### ISSUE THREAD

**Issue by iamyogik** [zuimeiaj/yoyoo-ddr#19]
When  `parent = true`,  we are able to restrict the cell from going out of the parent component.
But still when we resize the cell, it goes out of the parent element. Can we do something to stop that?

Eg: 
![image](https://user-images.githubusercontent.com/26013245/132737367-0989b00e-11e9-4dda-ac7b-1691b809546c.png)

**Comment by zuimeiaj** [comment]
parent=true only acts on dragging, and it is planned to provide support for rotation and resizing in future versions

**Comment by iamyogik** [comment]
Awesome, thanks
