### ISSUE TITLE
TypeError: e is not a function at eval (yoyoo-ddr.umd.min.js?fc67:1)

### ISSUE THREAD

**Issue by Sanan4li** [zuimeiaj/yoyoo-ddr#20]
I just installed the package with vue 3 and I am facing this issue. 
![image](https://user-images.githubusercontent.com/45590156/135998067-3b1e19ee-c061-45cd-836a-a9de03c582a5.png)

**Comment by zuimeiaj** [comment]
vue3 uses npm i yoyoo-ddr-vue3
