### ISSUE TITLE
Transform is shifted from mouse position

### ISSUE THREAD

**Issue by jvolker** [zuimeiaj/yoyoo-ddr#34]
Thanks for creating this.

I'm using this simple example with Vue 3 and  yoyoo-ddr-vue3 version 1.0.2:
```
<template>
  <DDR v-model:value="transform">
    <div style="background:red;width:100%;height:100%">{{transform}}</div>
  </DDR>
</template>

<script>

import DDR from 'yoyoo-ddr-vue3'
import 'yoyoo-ddr-vue3/dist/yoyoo-ddr-vue3.css'

export default {
  components: {
    DDR
  },
  data() {
    return {
      transform: { x: 100, y: 100, width: 100, height: 100, rotation: 0 },
    }
  }
}
</script>


```

Unfortunately, as soon as I drag the mouse on one of the handles the transform doesn't seem to match the mouse position and is shifted slightly. Left and right handles seem to be okay.

https://user-images.githubusercontent.com/546852/169341448-2a4b63c8-92cc-4683-98ba-2ada369595fa.mov

**Comment by zuimeiaj** [comment]
Thank you for raising this bug, it has been fixed in the new version

**Comment by zuimeiaj** [comment]
Thank you for raising this bug, it has been fixed in the new version
