### ISSUE TITLE
在Vue3中使用:value传入默认值，触发resize宽高会变为1

### ISSUE THREAD

**Issue by xiangzy1** [zuimeiaj/yoyoo-ddr#37]
`<template>
    <DDR
      class="item-wrap"
      :active="true"
      :value="{ x: 100, y: 100, width: 200, height: 200, rotation: 0 }"
    / >
<template>`

**Comment by zuimeiaj** [comment]
@xiangzy1  可否录个视频呢，无法重现你说的问题。

**Comment by xiangzy1** [comment]
npm install了一下 就好了..
