### ISSUE TITLE
Is there any way to detect if one component is over another?

### ISSUE THREAD

**Issue by pnavarretec01** [zuimeiaj/yoyoo-ddr#55]
I need to detect when a component is over another component, but not by coordinates, I need to detect if they touch and get their attributes.

Is this possible?

I'm using VUE 2
![code](https://user-images.githubusercontent.com/60895284/197818044-a74779ef-ba1e-4782-a661-2cbba8aec555.jpg)

**Comment by zuimeiaj** [comment]
Judge whether the component position intersects with other components in the drag event

**Comment by pnavarretec01** [comment]
> Judge whether the component position intersects with other components in the drag event

![image](https://user-images.githubusercontent.com/60895284/208522600-c7de89be-3eaa-4681-a82d-04b977e36e99.png)


I have a line where I am placing components, but my validation only takes into account from the beginning of the component and does not take into account the end of it, so it is not very useful for me, how could I validate or obtain this information?

For example, in the image, when locating the component on the vertical line, it is validated with its coordinate, but it only takes it into account with the start of the green component.
