### ISSUE TITLE
当父层级进行缩放时改变大小有问题

### ISSUE THREAD

**Issue by 3200875391** [zuimeiaj/yoyoo-ddr#6]
感谢作者开发这个组件给我减轻了很多麻烦，我发现通过transform: scale(0.5)控制父层级的缩放程度时，再去拖动改变组件的大小时，会出现错乱的情况，
再次感谢作者开发这个组件，但还是希望作者可以给我提供一下解决的思路

**Comment by zhixuefang** [comment]
我现在也遇到同样的问题，请问已经有解决方案了吗？

**Comment by zuimeiaj** [comment]
该组件并没有对缩放进行支持
