### ISSUE TITLE
know xy end position of the component

### ISSUE THREAD

**Issue by pnavarretec01** [zuimeiaj/yoyoo-ddr#68]
For the creator of the library I have a query :(
Just as I have the initial xy position of the component, is it possible to know its final position without having to do it manually? through some algorithm or something?

![Captura de pantalla 2023-04-26 142252](https://user-images.githubusercontent.com/60895284/234668369-6eef1e07-9acb-4757-bfcb-6ccbcd36997d.png)

**Comment by zuimeiaj** [comment]
You can use the x in tansform plus the width property

**Comment by ahmedmaghraby** [comment]
you have a start point and width  so you can get with just sum x + width

**Comment by pnavarretec01** [comment]
> you have a start point and width so you can get with just sum x + width

thanks! But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?

**Comment by pnavarretec01** [comment]
> You can use the x in tansform plus the width property

But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?

**Comment by pnavarretec01** [comment]
> > > You can use the x in tansform plus the width property
> > 
> > 
> > But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?
> 
> sorry, my friend I didn't see your reply, you have an old y point and angle of rotation so you calculate a new y point easily you can use my function `
> 
> > function calculateNewPoint(y1, angleDegrees, length) {
> > const angleRadians = angleDegrees * Math.PI / 180;
> > const y2 = y1 + length * Math.sin(angleRadians);
> > return { y: y2 };
> > }
> 
> `
> 
> function parameters are old y point and angle and length and output is your new y point if you have other questions don't hesitate to ask

thanks!
y1 is the starting point of y? and length is the width?
I'm sorry, I have a question, would the new point be the final point?
I ask, because, I am validating when an "object" is placed on the line that I am validating, but to do so I must have all the points and through which the line passes to validate, not only the beginning and the end, or my logic is failing and is there a simpler way? haha
I would really appreciate your answer

**Comment by pnavarretec01** [comment]
> > > You can use the x in tansform plus the width property
> > 
> > 
> > But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?
> 
> sorry, my friend I didn't see your reply, you have an old y point and angle of rotation so you calculate a new y point easily you can use my function `
> 
> > function calculateNewPoint(y1, angleDegrees, length) {
> > const angleRadians = angleDegrees * Math.PI / 180;
> > const y2 = y1 + length * Math.sin(angleRadians);
> > return { y: y2 };
> > }
> 
> `
> 
> function parameters are old y point and angle and length and output is your new y point if you have other questions don't hesitate to ask

thanks!
y1 is the starting point of y? and length is the width?
I'm sorry, I have a question, would the new point be the final point?
I ask, because, I am validating when an "object" is placed on the line that I am validating, but to do so I must have all the points and through which the line passes to validate, not only the beginning and the end, or my logic is failing and is there a simpler way? haha
I would really appreciate your answer

**Comment by ahmedmaghraby** [comment]
> > > > You can use the x in tansform plus the width property
> > > 
> > > 
> > > But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?
> > 
> > 
> > sorry, my friend I didn't see your reply, you have an old y point and angle of rotation so you calculate a new y point easily you can use my function `
> > > function calculateNewPoint(y1, angleDegrees, length) {
> > > const angleRadians = angleDegrees * Math.PI / 180;
> > > const y2 = y1 + length * Math.sin(angleRadians);
> > > return { y: y2 };
> > > }
> > 
> > 
> > `
> > function parameters are old y point and angle and length and output is your new y point if you have other questions don't hesitate to ask
> 
> thanks! y1 is the starting point of y? and length is the width? I'm sorry, I have a question, would the new point be the final point? I ask, because, I am validating when an "object" is placed on the line that I am validating, but to do so I must have all the points and through which the line passes to validate, not only the beginning and the end, or my logic is failing and is there a simpler way? haha I would really appreciate your answer


y is the first y point 
![image](https://github.com/zuimeiaj/yoyoo-ddr/assets/38741761/14af9291-e50b-4e89-a32f-0c721f411baa)

and length is half of the width because the item rotates around the central point, not around the x point.

sorry my friend I don't understand your business well so I can't help  you to find optimal solution for your case

**Comment by pnavarretec01** [comment]
> > > > > You can use the x in tansform plus the width property
> > > > 
> > > > 
> > > > But if I have, for example, a diagonal line with a 45 degree rotation, is there a way to obtain all the variations of points x and y?
> > > 
> > > 
> > > sorry, my friend I didn't see your reply, you have an old y point and angle of rotation so you calculate a new y point easily you can use my function `
> > > > function calculateNewPoint(y1, angleDegrees, length) {
> > > > const angleRadians = angleDegrees * Math.PI / 180;
> > > > const y2 = y1 + length * Math.sin(angleRadians);
> > > > return { y: y2 };
> > > > }
> > > 
> > > 
> > > `
> > > function parameters are old y point and angle and length and output is your new y point if you have other questions don't hesitate to ask
> > 
> > 
> > thanks! y1 is the starting point of y? and length is the width? I'm sorry, I have a question, would the new point be the final point? I ask, because, I am validating when an "object" is placed on the line that I am validating, but to do so I must have all the points and through which the line passes to validate, not only the beginning and the end, or my logic is failing and is there a simpler way? haha I would really appreciate your answer
> 
> y is the first y point ![image](https://user-images.githubusercontent.com/38741761/242044654-14af9291-e50b-4e89-a32f-0c721f411baa.png)
> 
> and length is half of the width because the item rotates around the central point, not around the x point.
> 
> sorry my friend I don't understand your business well so I can't help you to find optimal solution for your case

For example, I need to validate when item k6598 is on the red line, to validate on lines with 0 rotation is easy, because it has a start - end, "y" point and fixed, but if the line has, for example, a rotation of 45 degrees, I need to validate through the "y" point, but it will have many, and with that validation I'm stuck :( hahah

![red](https://github.com/zuimeiaj/yoyoo-ddr/assets/60895284/a334ca0c-5805-4367-8bfa-3ecffd3872c9)

**Comment by zuimeiaj** [comment]
@pnavarretec01 

https://github.com/zuimeiaj/yoyoo-ddr/assets/11345054/1ff6f4b2-be52-42bc-8125-f09cc6bc4a3a

Is this what you want?

**Comment by pnavarretec01** [comment]
> @pnavarretec01
> 
>  z7k43-eeuis.mp4 
> Is this what you want?

how did you do it? :O hahaha, what I am doing is having lines that are valid and others that are not to position an element on them, those that are not valid throw me an alert and those that are valid allow me to do the logic of my project, but I have the problem of how to validate when the line has a rotation since it does not have a fixed point to do this, I think that what you have might help me :o

**Comment by zuimeiaj** [comment]
@pnavarretec01 
You can run the code below to see if it meets your needs
`<script>
import DDR from 'yoyoo-ddr';
import 'yoyoo-ddr/dist/yoyoo-ddr.css';
export default {
  data() {
    return {
      transform: { x: 100, y: 100, width: 500, height: 100, rotation: 0 },
      point: { x: 0, y: 0 },
      point2: { x: 0, y: 0 },
    };
  },
  watch: {
    transform(v) {
      let rad = (45 * Math.PI) / 180;
      let x = v.y / Math.tan(rad);
      let x1 = (v.height + v.y) / Math.tan(rad);
      this.point = {
        x: this.line.left + x,
        y: v.y,
      };
      this.point2 = {
        x: this.line.left + x1,
        y: v.y + v.height,
      };
    },
  },

  mounted() {
    this.line = this.$refs.line.getBoundingClientRect();
  },
  render() {
    return (
      <div class='twowaybind page'>
        <div ref='line' class='line-r45'></div>

        <div style={`left:${this.point.x}px;top:${this.point.y}px`} class='guide-point'>
          <span>
            x:{this.point.x.toFixed(0)}, y:{this.point.y.toFixed(2)}
          </span>
        </div>
        <div style={`left:${this.point2.x}px;top:${this.point2.y}px`} class='guide-point'>
          <span>
            x:{this.point2.x.toFixed(0)}, y:{this.point2.y.toFixed(2)}
          </span>
        </div>

        <DDR minHeight={100} minWidth={300} parent={true} v-model={this.transform}>
          <div class='cell' />
        </DDR>
      </div>
    );
  },
};
</script>

<style lang="less" scoped>
.guide-point {
  position: absolute;
  left: 0;
  top: 0;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: red;
  transform: translate(-50%, -50%);
  span {
    position: absolute;
    display: block;
    width: 200px;
    top: -10px;
    left: 10px;
  }
}
.guide-line-x,
.guide-line-y {
  position: absolute;
  height: 0;
  width: 0;
  left: 0;
  top: 0;
}
.guide-line-x {
  border-top: 1px dashed red;
}
.guide-line-y {
  border-left: 1px dashed red;
}
.twowaybind {
  .line-r45 {
    height: 1px;
    width: 1000px;
    position: absolute;
    left: 500px;
    top: 0px;
    background: black;
    transform: rotate(45deg);
    transform-origin: top left;
  }
  .tips {
    text-align: center;
    padding: 24px;
  }
  .cell {
    background: grey;
    color: #fff;
    height: 100%;
    user-select: none;
    padding: 24px;
  }
}
</style>
`
