### ISSUE TITLE
当锁死宽高比的时候拖拉组件 组件偶尔会产生变形

### ISSUE THREAD

**Issue by clm2733227** [zuimeiaj/yoyoo-ddr#7]

**Comment by zuimeiaj** [comment]
没有出现你说的这种情况呢

**Comment by clm2733227** [comment]
> 没有出现你说的这种情况呢，可以录一个重现的视频吗

![image](https://user-images.githubusercontent.com/14868071/119797994-5535c780-bf0d-11eb-8b3e-20e0cdb11a0b.png)

**Comment by clm2733227** [comment]
> 没有出现你说的这种情况呢，可以录一个重现的视频吗![image](

**Comment by clm2733227** [comment]
![done](https://user-images.githubusercontent.com/14868071/119803505-19513100-bf12-11eb-8d59-78206ad37d2a.gif)

**Comment by clm2733227** [comment]
> 没有出现你说的这种情况呢，可以录一个重现的视频吗

如上所示，请查看

**Comment by zuimeiaj** [comment]
好的，确实有问题

**Comment by zuimeiaj** [comment]
The issue is that the aspect ratio changes during resizing.

**Comment by clm2733227** [comment]
> 

This issue seems already fixed.
